src/Entity/Objectif.php
<?php

namespace App\Entity;

use App\Repository\ObjectifRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ObjectifRepository::class)]
class Objectif
{
    public function __construct()
    {
        $this->CreatedAt = new \DateTimeImmutable();
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'objectifs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Domaine $domaine = null;

    #[ORM\ManyToOne(inversedBy: 'objectifs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Libelle $Libelle = null;

    #[ORM\Column(length: 100)]
    private ?string $valeur = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $CreatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'objectifs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(nullable:true)]
    private ?\DateTimeImmutable $endAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?Libelle
    {
        return $this->Libelle;
    }

    public function setLibelle(?Libelle $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getDomaine(): ?Domaine
    {
        return $this->domaine;
    }

    public function setDomaine(?Domaine $domaine): self
    {
        $this->domaine = $domaine;

        return $this;
    }

    public function getValeur(): ?string
    {
        return $this->valeur;
    }

    public function setValeur(string $valeur): self
    {
        $this->valeur = $valeur;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Set the value of id
     *
     * @return  self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(\DateTimeImmutable $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }
}

src/Form/ObjectifType.php
<?php

namespace App\Form;

use App\Entity\Objectif;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ObjectifType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('domaine')
            ->add('Libelle')
            ->add('valeur');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Objectif::class,
        ]);
    }
}

src/Controller/ObjectifController.php
<?php

namespace App\Controller;

use App\Entity\Objectif;
use App\Form\ObjectifType;
use App\Repository\ObjectifRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/objectif')]
class ObjectifController extends AbstractController
{
    #[Route('/', name: 'app_objectif_index', methods: ['GET'])]
    public function index(ObjectifRepository $objectifRepository): Response
    {
        return $this->render('objectif/index.html.twig', [
            'objectifs' => $objectifRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_objectif_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ObjectifRepository $objectifRepository): Response
    {
        $objectif = new Objectif();
        $form = $this->createForm(ObjectifType::class, $objectif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlash(
                'success',
                'Les informations de votre objectif ont bien été ajoutées.'
            );
            $objectif->setUser($this->getUser());
            $objectifRepository->save($objectif, true);
            return $this->redirectToRoute('app_board');
        }

        return $this->renderForm('objectif/new.html.twig', [
            'objectif' => $objectif,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_objectif_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Objectif $objectif, ObjectifRepository $objectifRepository): Response
    {
        $form = $this->createForm(ObjectifType::class, $objectif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlash(
                'success',
                'Les informations de votre objectif ont bien été modifiées.'
            );
            $objectifRepository->save($objectif, true);
            return $this->redirectToRoute('app_board');
        }

        return $this->renderForm('objectif/edit.html.twig', [
            'objectif' => $objectif,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_objectif_delete', methods: ['POST'])]
    public function delete(Request $request, Objectif $objectif, ObjectifRepository $objectifRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $objectif->getId(), $request->request->get('_token'))) {
            $objectifRepository->remove($objectif, true);
            $this->addFlash(
                'danger',
                'Votre objectif a bien été supprimé.'
            );
        }
        return $this->redirectToRoute('app_board');
    }
}

templates/objectif/_delete_form.html.twig
<form method="post" action="{{ path('app_objectif_delete', {'id': objectif.id}) }}"
    onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ objectif.id) }}">
    <button class="btn" style="font-size: 16px;">Supprimer</button>
</form>

templates/objectif/_form.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}Hello ObjectifController!{% endblock %}

{% block body %}

<div class="row" style="max-width: 100%;">
    <fieldset class="" style="border-color: orange;">
        <div style="align-items: center;">
            {{ form_start(form) }}
            <div id="padding" style="padding-left: 90px;">
                <div class="col-lg-9 col-sm-9">
                    {{ form_widget(form) }}
                </div>
                <div class="row mt-4">
                    <div class="col-4">
                        <a class="btn btn-primary" href="{{ path('app_board') }}"
                            style="color: white; margin-left: 5px;">Retour</a>
                    </div>
                    <div class="col-1">

                    </div>
                    <div class="col-3">
                        <button class="btn">{{ button_label|default('Valider') }}</button>
                    </div>
                </div>

                {{ form_end(form) }}
            </div>
    </fieldset>
    <div class="">
        <!-- <img src="assets/img/image_header.svg" alt="" loading="lazy" /> -->
    </div>
</div>

{% block style%}

<style>
    @media screen and (max-width : 640px) {

        #padding {
            padding-left: 0px !important;
        }

        .mt-4 {
            padding-left: 61px;
        }

        .col-3 {
            padding-left: 15px;
        }
    }
</style>

{% endblock %}
{% endblock %}

templates/objectif/edit.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}Edit Objectif{% endblock %}

{% block content %}
<div class="mb-5">
    <a href="{{ path('app_home') }}"><img src="assets/images/Logo.png" alt="" loading="lazy"
            style="height: 100px;margin-left:90px" /></a>
</div>
<div class="row">
    <div class="col-3">
    </div>
    <div class="col-lg-6">
        <div class="container" id="saisie-objectif" style="background-color: white;">
            <h1 style="font-size: 25px; text-align: center;">Modification de l'Objectif</h1>
            <div>
                {{ include('objectif/_form.html.twig', {'button_label': 'Update'}) }}
            </div>
        </div>
    </div>
    <div class="col-2">
    </div>
</div>

{% block style%}

<style>
    @media screen and (max-width : 640px) {}
</style>

{% endblock %}

{% endblock %}

templates/objectif/index.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}Objectifs{% endblock %}

{% block content %}

<div class="container">
    <a class="btn btn-primary" href="{{ path('app_board')}}" style="font-size: 16px; color: white;">Retour</a>
    <h1 style="font-size: 25px; text-align: center; margin-bottom: 15px;  margin-top: 15px;">Objectifs </h1>

    <div style="overflow-x: auto;">
        <table class="table table-hover" style="background-color: white;">
            <thead>
                <tr>
                    <th scope="col">
                        <p>Domaine</p>
                    </th>
                    <th scope="col">
                        <p>Libelle</p>
                    </th>
                    <th scope="col">
                        <p>Valeur</p>
                    </th>
                    <th scope="col">
                        <p>Unité</p>
                    </th>
                    <th scope="col">
                        <p>Date</p>
                    </th>
                    <th scope="col">
                        <p>Actions</p>
                    </th>
                </tr>
            </thead>
            <tbody>

            {% for objectif in app.user.objectifs %}
            <tr>
                <td>
                    <p>{{objectif.domaine.libelle}}</p>
                </td>
                <td>
                    <p>{{objectif.libelle.label}}</p>
                </td>
                <td>
                    <p>{{objectif.valeur}}</p>
                </td>
                <td>
                    <p>{{objectif.libelle.unit}}</p>
                </td>
                <td>
                    <p>{{objectif.CreatedAt|date("m/d/Y")}}</p>
                </td>
                <td class="d-flex gap-3">
                    <a class="btn btn-primary" href="{{ path('app_objectif_edit', {'id': objectif.id}) }}"
                        style="font-size: 16px; color: white;">Modifier</a>
                    {{ include('objectif/_delete_form.html.twig') }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-primary" href="{{ path('app_objectif_new') }}"> Nouveau</a>


</div>

{% endblock %}

templates/objectif/new.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}New Objectif{% endblock %}

{% block content %}
<div class="mb-5">
    <a href="{{ path('app_home') }}"><img src="assets/images/Logo.png" alt="" loading="lazy"
            style="height: 100px;margin-left:90px" /></a>
</div>
<div class="row">
    <div class="col-3">
    </div>
    <div class="col-lg-6">
        <div class="container" id="saisie-objectif" style="text-align: center; background-color: white;">
            <h1 style="font-size: 25px;">Créer l'Objectif de la semaine</h1>
            {{ include('objectif/_form.html.twig') }}
        </div>
    </div>
    <div class="col-2">
    </div>
</div>

{% block style%}

<style>
    @media screen and (max-width : 640px) {}
</style>

{% endblock %}

{% endblock %}